import { CheckCircle, X } from "@phosphor-icons/react";
import { useEffect, useState } from "react";
import { allServices, calculateQuote, contact, formatPrice } from "../data/pricing";

interface Props { isOpen:boolean; onClose:()=>void; selectedServices:string[]; onToggleService:(name:string)=>void }
export default function ModalFlow({isOpen,onClose,selectedServices,onToggleService}:Props){
  const [step,setStep]=useState(1); const [contactInfo,setContactInfo]=useState(""); const [message,setMessage]=useState(""); const [submitting,setSubmitting]=useState(false); const [success,setSuccess]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{if(isOpen){setStep(1);setSuccess(false);setError("")}document.body.style.overflow=isOpen?"hidden":"";return()=>{document.body.style.overflow=""}},[isOpen]);
  if(!isOpen)return null;
  const quote=calculateQuote(selectedServices);
  const submit=async()=>{if(!contactInfo.trim())return;setSubmitting(true);setError("");try{const response=await fetch("/.netlify/functions/submit-lead",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contact:contactInfo.trim(),services:selectedServices,total:quote.total,paymentRule:quote.paymentRule,upfrontPayment:quote.upfrontPayment,message,timestamp:new Date().toISOString()})});if(!response.ok)throw new Error();setSuccess(true)}catch{setError(`提交失败，请重试或直接联系向先生（微信/电话）：${contact.phone}`)}finally{setSubmitting(false)}};
  return <div className="modal-backdrop" onClick={onClose}><div className="modal-panel" onClick={event=>event.stopPropagation()}><header><span>{success?"咨询已提交":`步骤 ${step} / 3`}</span><button onClick={onClose} aria-label="关闭"><X weight="bold"/></button></header><div className="modal-body">
    {success?<div className="modal-success"><CheckCircle size={64} weight="fill"/><h3>提交成功</h3><p>向先生会尽快联系你，请保持通讯畅通</p><strong>联系人：向先生 · 微信 / 电话：{contact.wechat}</strong></div>:step===1?<div><h3>选择需要的服务</h3><div className="modal-services">{allServices.map(item=><label key={item.name} className={selectedServices.includes(item.name)?"selected":""}><input type="checkbox" checked={selectedServices.includes(item.name)} onChange={()=>onToggleService(item.name)}/><span>{item.name}</span><strong>{formatPrice(item)}</strong></label>)}</div></div>:step===2?<div><h3>起步估价与付款方式</h3><div className="modal-quote"><span>已选：{selectedServices.join("、")||"待沟通"}</span><strong>¥{quote.total.toLocaleString("zh-CN")}</strong><p>{quote.paymentRule}</p><p>开工款：¥{quote.upfrontPayment.toLocaleString("zh-CN")}</p></div><small>此处为公开最低价估算，最终以书面功能清单为准。</small></div>:<div><h3>留下联系方式</h3><p className="contact-owner">联系人：向先生 · 微信 / 电话 {contact.phone}</p><input value={contactInfo} onChange={e=>setContactInfo(e.target.value)} placeholder="你的电话或微信（必填）"/><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={4} placeholder="简单描述项目需求（选填）"/>{error&&<p className="modal-error">{error}</p>}<button onClick={submit} disabled={!contactInfo.trim()||submitting} className="button button-primary submit-button">{submitting?"提交中…":"提交咨询"}</button></div>}
  </div>{!success&&step<3&&<footer>{step>1&&<button onClick={()=>setStep(step-1)} className="button button-outline">返回</button>}<button onClick={()=>setStep(step+1)} className="button button-primary">下一步</button></footer>}</div></div>
}
